{
	"version": 1689786710,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bgpilihan-sheet0.png",
		"images/tombolkeluar-sheet0.png",
		"images/musicon-sheet0.png",
		"images/musicon-sheet1.png",
		"images/tombolprofil-sheet0.png",
		"images/tombolpetunjuk-sheet0.png",
		"images/judul-sheet0.png",
		"images/tombolkiri-sheet0.png",
		"images/tombolkanan-sheet0.png",
		"images/tombolevaluasi-sheet0.png",
		"images/tombolmateri-sheet0.png",
		"images/papanputih-sheet0.png",
		"images/tombolhome-sheet0.png",
		"images/tombolhome-sheet1.png",
		"images/isimateri-sheet0.png",
		"images/isimateri-sheet1.png",
		"images/hitampopup-sheet0.png",
		"images/papanpopup-sheet0.png",
		"images/closepengembang-sheet0.png",
		"images/tekspengembang-sheet0.png",
		"images/papanquiz-sheet0.png",
		"images/papanjawaban-sheet0.png",
		"images/soal-sheet0.png",
		"images/soal-sheet1.png",
		"images/jawaban-sheet0.png",
		"images/jawaban-sheet1.png",
		"images/jawaban-sheet2.png",
		"images/jawaban-sheet3.png",
		"images/jawaban-sheet4.png",
		"images/jawaban-sheet5.png",
		"images/jawaban-sheet6.png",
		"images/jawaban-sheet7.png",
		"images/jawaban-sheet8.png",
		"images/jawaban-sheet9.png",
		"images/pjawaban-sheet0.png",
		"images/papanskor-sheet0.png",
		"images/particleskor.png",
		"images/logo-sheet0.png",
		"images/tekskeluar-sheet0.png",
		"images/jangankeluar-sheet0.png",
		"images/keluar-sheet0.png",
		"images/bgloading-sheet0.png",
		"images/loadingbar-sheet0.png",
		"images/loadingbar-sheet1.png",
		"images/teksnavigasi-sheet0.png",
		"images/bgpilihan1-sheet0.png",
		"images/bgpilihan1-sheet1.png",
		"images/bgpilihan1-sheet2.png",
		"images/bgpilihan1-sheet3.png",
		"images/putihpapan.png",
		"images/menupilihan-sheet0.png",
		"images/hitammenu.png",
		"images/bgmenu-sheet0.png",
		"images/angklung-sheet0.png",
		"images/tifa-sheet0.png",
		"images/tomboltifa-sheet0.png",
		"images/gangsa-sheet0.png",
		"images/tombolgangsa-sheet0.png",
		"images/taligangsa-sheet0.png",
		"images/garantung-sheet0.png",
		"images/tombolgarantung-sheet0.png",
		"images/tombolgarantung-sheet1.png",
		"images/tombolgarantung-sheet2.png",
		"images/tombolgarantung-sheet3.png",
		"images/tombolgarantung-sheet4.png",
		"images/tombolgarantung-sheet5.png",
		"images/tombolgarantung-sheet6.png",
		"images/tombolgarantung-sheet7.png",
		"images/tombolgarantung-sheet8.png",
		"images/taligarantung-sheet0.png",
		"images/kolintang-sheet0.png",
		"images/tombolkolintang-sheet0.png",
		"images/titikkolintang-sheet0.png",
		"images/teksangklung-sheet0.png",
		"images/teksgangsa-sheet0.png",
		"images/tekstifa-sheet0.png",
		"images/teksgarantung-sheet0.png",
		"images/tekskolintang-sheet0.png",
		"images/tempatangklung-sheet0.png",
		"images/stop-sheet0.png",
		"images/play-sheet0.png",
		"images/ulang-sheet0.png",
		"images/layarnotif-sheet0.png",
		"images/salah-sheet0.png",
		"images/salah-sheet1.png",
		"images/salah-sheet2.png",
		"images/mulai-sheet0.png",
		"images/giliran-sheet0.png",
		"images/tirukan-sheet0.png",
		"images/papanlevel-sheet0.png",
		"images/level-sheet0.png",
		"images/level-sheet1.png",
		"images/level-sheet2.png",
		"images/level2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/burung-sheet0.png",
		"images/burung-sheet1.png",
		"images/jalan-sheet0.png",
		"images/ikonangklung-sheet0.png",
		"images/ikonangklung-sheet1.png",
		"images/ikonangklung-sheet2.png",
		"images/ikonangklung-sheet3.png",
		"images/ikonangklung-sheet4.png",
		"images/ikonangklung-sheet5.png",
		"media/gangsa 1.ogg",
		"media/gangsa 2.ogg",
		"media/gangsa 3.ogg",
		"media/gangsa 4.ogg",
		"media/gangsa 5.ogg",
		"media/gangsa 6.ogg",
		"media/gangsa 7.ogg",
		"media/garantung 9.ogg",
		"media/garantung 8.ogg",
		"media/garantung 7.ogg",
		"media/garantung 6.ogg",
		"media/garantung 5.ogg",
		"media/garantung 4.ogg",
		"media/garantung 3.ogg",
		"media/garantung 2.ogg",
		"media/garantung 1.ogg",
		"media/kolintang 1.ogg",
		"media/kolintang 2.ogg",
		"media/kolintang 3.ogg",
		"media/kolintang 4.ogg",
		"media/kolintang 5.ogg",
		"media/kolintang 6.ogg",
		"media/kolintang 7.ogg",
		"media/kolintang 8.ogg",
		"media/kolintang 9.ogg",
		"media/tombol.m4a",
		"media/tombol.ogg",
		"media/angklung.ogg",
		"media/tifa.ogg",
		"media/backsound.m4a",
		"media/backsound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"gangsa.mp4"
	]
}